[package]
name = "cute-vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
clap = { version = "3.1.6", features = ["derive"] }
lazy_static = "1.4.0"
log = "0.4.17"
env_logger = "0.10.0"

num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
